source("count.R")
count("other")
num <- count("unknown")
print(num)
source("http://spark-public.s3.amazonaws.com/compdata/scripts/submitscript4.R")
submit()
source("agecount.R")
agecount(3)
agecount(21)